import { Product } from './supabase'

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'AI Prompt Vault',
    slug: 'ai-prompt-vault',
    description: 'A curated collection of 500+ battle-tested prompts for ChatGPT, Claude, and Midjourney. Organized by category with real-world examples and output samples.\n\n## What\'s Inside\n\n- 500+ prompts across 12 categories\n- Copy-paste ready templates\n- Variable placeholders for customization\n- Output examples for each prompt\n- Regular updates with new prompts',
    short_desc: 'A curated collection of 500+ battle-tested AI prompts.',
    price_cents: 0,
    type: 'free',
    category: 'toolkit',
    file_path: null,
    demo_url: null,
    thumbnail_url: null,
    features: ['500+ curated prompts', '12 categories', 'Copy-paste ready', 'Regular updates', 'ChatGPT, Claude & Midjourney'],
    is_published: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Invoice Generator',
    slug: 'ai-invoice-generator',
    description: 'AI-powered invoice generator that creates professional invoices in seconds. Built with Next.js and ready to deploy.\n\n## Features\n\n- Auto-fill client details with AI\n- PDF export\n- Multi-currency support\n- Custom branding\n- Tax calculations',
    short_desc: 'AI-powered invoice generator. Professional invoices in seconds.',
    price_cents: 2900,
    type: 'paid',
    category: 'template',
    file_path: null,
    demo_url: null,
    thumbnail_url: null,
    features: ['AI auto-fill', 'PDF export', 'Multi-currency', 'Custom branding', 'Tax calculations', 'Next.js source code'],
    is_published: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Content Creator Toolkit',
    slug: 'content-creator-toolkit',
    description: 'Everything you need to create content faster with AI. Includes templates for blog posts, social media, email campaigns, and video scripts.\n\n## Includes\n\n- 50+ content templates\n- AI workflow automations\n- Social media calendar\n- Analytics dashboard template\n- Video script generator',
    short_desc: 'Complete AI content creation toolkit with 50+ templates.',
    price_cents: 4900,
    type: 'paid',
    category: 'toolkit',
    file_path: null,
    demo_url: null,
    thumbnail_url: null,
    features: ['50+ templates', 'AI workflows', 'Social calendar', 'Analytics dashboard', 'Video scripts', 'Email templates'],
    is_published: true,
    sort_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'AI Starter Bundle',
    slug: 'ai-starter-bundle',
    description: 'Get all current tools and templates in one bundle at a massive discount. Includes everything in the store plus future updates.\n\n## Bundle Includes\n\n- AI Prompt Vault\n- Invoice Generator\n- Content Creator Toolkit\n- All future products (lifetime access)\n- Priority support',
    short_desc: 'All tools + future updates. The complete AI toolkit.',
    price_cents: 7900,
    type: 'bundle',
    category: 'toolkit',
    file_path: null,
    demo_url: null,
    thumbnail_url: null,
    features: ['All current products', 'Lifetime updates', 'Future products included', 'Priority support', 'Commercial license'],
    is_published: true,
    sort_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'AI Filmmaking Masterclass',
    slug: 'ai-filmmaking-masterclass',
    description: 'Learn how to integrate AI into your filmmaking workflow. From pre-production to post, discover tools and techniques that save hours.\n\n## Curriculum\n\n- AI in pre-production planning\n- Script analysis with LLMs\n- AI-assisted color grading\n- Automated subtitles and translations\n- AI sound design',
    short_desc: 'Master AI tools for modern filmmaking workflows.',
    price_cents: 14900,
    type: 'premium',
    category: 'course',
    file_path: null,
    demo_url: null,
    thumbnail_url: null,
    features: ['5+ hours of content', 'Practical workflows', 'Tool recommendations', 'Project files included', 'Community access', 'Certificate'],
    is_published: true,
    sort_order: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Social Media AI Kit',
    slug: 'social-media-ai-kit',
    description: 'AI-powered social media management templates and automations. Schedule, create, and analyze content across platforms.\n\n## Features\n\n- Post generators for all platforms\n- Hashtag research tool\n- Content calendar template\n- Engagement analytics\n- Caption writer',
    short_desc: 'AI-powered templates for social media management.',
    price_cents: 0,
    type: 'free',
    category: 'template',
    file_path: null,
    demo_url: null,
    thumbnail_url: null,
    features: ['Multi-platform support', 'Hashtag research', 'Content calendar', 'Caption generator', 'Analytics tracking'],
    is_published: true,
    sort_order: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'AI Meeting Report',
    slug: 'ai-meeting-report',
    description: 'Turn any meeting into a polished, structured report — automatically. This tool uses AI to summarize transcripts, extract action items, and generate a professional PDF report you can share with your team.\n\n## What\'s Inside\n\n- AI-powered meeting summarizer\n- Action item extraction\n- Professional PDF report output\n- Speaker attribution\n- Key decisions and highlights',
    short_desc: 'AI-powered meeting summarizer that generates professional PDF reports.',
    price_cents: 0,
    type: 'free',
    category: 'template',
    file_path: 'https://byyqqelacuorqpnxfhmv.supabase.co/storage/v1/object/public/ai.ivrifogel.com/meeting-report.zip',
    demo_url: null,
    thumbnail_url: 'https://byyqqelacuorqpnxfhmv.supabase.co/storage/v1/object/public/ai.ivrifogel.com/meeting-report.png',
    features: ['AI meeting summarization', 'Action item extraction', 'Professional PDF output', 'Speaker attribution', 'Key decisions & highlights'],
    is_published: true,
    sort_order: 7,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
